const WeaponsNames = ['ACR', 'AK-15']

type WeaponsName = 'ACR' | 'AK-15' | 'AK-74'

export interface WeaponConfig {
  weaponType: string
  name: WeaponsName
  imageName: string
  hasModel?: boolean
  modelFov?: number
  unlockLevel?: number
}

export const weapons: WeaponConfig[] = [
  {
    name: 'ACR',
    imageName: 'ACR',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 18,
  },
  {
    name: 'AK-15',
    imageName: 'AK15',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 10,
  },
  {
    name: 'AK-74',
    imageName: 'AK74',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 0,
  },
  {
    name: 'AUG-A3',
    imageName: 'AUGA3',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 19,
  },
  {
    name: 'SG 550',
    imageName: 'SG550',
    hasModel: true,
    modelFov: 3.5,
    weaponType: 'automatic-rifles',
    unlockLevel: 19,
  },
  {
    name: 'FAL',
    imageName: 'FAL',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 22,
  },
  {
    name: 'G36C',
    imageName: 'G36C',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 25,
  },
  {
    name: 'FAMAS',
    imageName: 'FAMAS',
    hasModel: true,
    modelFov: 4,
    unlockLevel: 28,
    weaponType: 'automatic-rifles',
  },
  {
    name: 'HK-419',
    imageName: 'HK419',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 37,
  },
  {
    name: 'M4A1',
    imageName: 'M4A1',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 0,
  },
  {
    name: 'SCAR-H',
    imageName: 'Scar-H',
    hasModel: true,
    modelFov: 4,
    weaponType: 'automatic-rifles',
    unlockLevel: 10,
  },
  {
    name: 'MP7',
    imageName: 'MP7',
    hasModel: true,
    modelFov: 4,
    weaponType: 'submachine-guns',
    unlockLevel: 0,
  },
  {
    name: 'UMP-45',
    imageName: 'UMP45',
    hasModel: true,
    modelFov: 4,
    weaponType: 'submachine-guns',
    unlockLevel: 0,
  },
  {
    name: 'PP-2000',
    imageName: 'PP2000',
    hasModel: true,
    modelFov: 3.5,
    weaponType: 'submachine-guns',
    unlockLevel: 13,
  },
  {
    name: 'PP-19',
    imageName: 'PP19',
    hasModel: true,
    modelFov: 3.5,
    weaponType: 'submachine-guns',
    unlockLevel: 22,
  },
  {
    name: 'Kriss Vector',
    imageName: 'KrissVector',
    hasModel: true,
    modelFov: 4,
    weaponType: 'submachine-guns',
    unlockLevel: 35,
  },
  {
    name: 'MP5',
    imageName: 'MP5',
    hasModel: true,
    modelFov: 4.5,
    weaponType: 'submachine-guns',
    unlockLevel: 43,
  },
  {
    name: 'MK-20',
    imageName: 'MK20',
    hasModel: true,
    modelFov: 4,
    weaponType: 'marksman-rifles',
    unlockLevel: 6,
  },
  {
    name: 'M110',
    imageName: 'M110',
    hasModel: true,
    modelFov: 4,
    weaponType: 'marksman-rifles',
    unlockLevel: 20,
  },
  {
    name: 'SVD',
    imageName: 'SVD',
    hasModel: true,
    modelFov: 4,
    weaponType: 'marksman-rifles',
    unlockLevel: 38,
  },
  {
    name: 'MK-14 EBR',
    imageName: 'MK14',
    hasModel: true,
    modelFov: 4,
    weaponType: 'marksman-rifles',
    unlockLevel: 50,
  },
  {
    name: 'Honey Badger',
    imageName: 'HoneyBadger',
    hasModel: true,
    modelFov: 3.5,
    weaponType: 'personal-defence',
    unlockLevel: 40,
  },
  {
    name: 'P90',
    imageName: 'P90',
    hasModel: true,
    modelFov: 3,
    weaponType: 'personal-defence',
    unlockLevel: 52,
  },
  {
    name: 'GROZA',
    imageName: 'GROZA',
    hasModel: true,
    modelFov: 4,
    weaponType: 'personal-defence',
    unlockLevel: 94,
  },
  {
    name: 'AS VAL',
    imageName: 'ASVAL',
    hasModel: true,
    modelFov: 3.5,
    weaponType: 'carbines',
    unlockLevel: 40,
  },
  {
    name: 'L86A1',
    imageName: 'L86A1',
    hasModel: true,
    modelFov: 6,
    weaponType: 'light-support-guns',
    unlockLevel: 0,
  },
  {
    name: 'M249',
    imageName: 'M249',
    hasModel: true,
    modelFov: 6,
    weaponType: 'light-support-guns',
    unlockLevel: 0,
  },
  {
    name: 'SSG 69',
    imageName: 'SSG69',
    hasModel: true,
    modelFov: 6,
    weaponType: 'sniper-rifles',
    unlockLevel: 0,
  },
  {
    name: 'SV-98',
    imageName: 'SV98',
    hasModel: true,
    modelFov: 6,
    weaponType: 'sniper-rifles',
    unlockLevel: 8,
  },
  {
    name: 'L96',
    imageName: 'L96',
    hasModel: true,
    modelFov: 6,
    weaponType: 'sniper-rifles',
    unlockLevel: 27,
  },
  {
    name: 'M200',
    imageName: 'M200',
    hasModel: true,
    modelFov: 6,
    weaponType: 'sniper-rifles',
    unlockLevel: 32,
  },
  {
    name: 'MSR',
    imageName: 'MSR',
    hasModel: true,
    modelFov: 6,
    weaponType: 'sniper-rifles',
    unlockLevel: 56,
  },
  {
    name: 'REM-700',
    imageName: 'REM700',
    hasModel: true,
    modelFov: 6,
    weaponType: 'sniper-rifles',
    unlockLevel: 72,
  },
  {
    name: 'M9',
    imageName: 'M9',
    hasModel: true,
    modelFov: 2.5,
    unlockLevel: 0,
    weaponType: 'pistols',
  },
  {
    name: 'MP443',
    imageName: 'M9',
    hasModel: true,
    modelFov: 2.5,
    unlockLevel: 0,
    weaponType: 'pistols',
  },
  {
    name: 'USP',
    imageName: 'USP',
    hasModel: true,
    modelFov: 2.5,
    unlockLevel: 7,
    weaponType: 'pistols',
  },
  {
    name: 'UNICA',
    imageName: 'UNICA',
    hasModel: true,
    modelFov: 2.5,
    unlockLevel: 12,
    weaponType: 'pistols',
  },
  {
    name: 'GLOCK 18',
    imageName: 'GLOCK18',
    hasModel: true,
    modelFov: 2.5,
    unlockLevel: 13,
    weaponType: 'pistols',
  },
  {
    name: 'Desert Eagle',
    imageName: 'DESERT-EAGLE',
    hasModel: true,
    modelFov: 2.5,
    unlockLevel: 60,
    weaponType: 'pistols',
  },
  {
    name: 'Pickaxe',
    imageName: 'Pickaxe',
    unlockLevel: 0,
    weaponType: 'misc',
  },
  {
    name: 'Sledgehammer',
    imageName: 'Sledgehammer',
    unlockLevel: 0,
    weaponType: 'misc',
  },
]

export type WeaponNames = keyof typeof weapons
