export interface WeaponData {
  weaponType: string
  name: string
  id: string
  hasModel?: boolean
  modelFov?: number
  unlockLevel?: number
}

export const weapons = {
  automaticRifles: [
    {
      name: 'ACR',
      id: 'ACR',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 18,
    },
    {
      name: 'AK-15',
      id: 'AK15',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 10,
    },
    {
      name: 'AK-74',
      id: 'AK74',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 0,
    },
    {
      name: 'AUG-A3',
      id: 'AUGA3',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 19,
    },
    {
      name: 'SG 550',
      id: 'SG550',
      hasModel: true,
      modelFov: 3.5,
      weaponType: 'automatic-rifles',
      unlockLevel: 19,
    },
    {
      name: 'FAL',
      id: 'FAL',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 22,
    },
    {
      name: 'G36C',
      id: 'G36C',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 25,
    },
    {
      name: 'FAMAS',
      id: 'FAMAS',
      hasModel: true,
      modelFov: 4,
      unlockLevel: 28,
      weaponType: 'automatic-rifles',
    },
    {
      name: 'HK-419',
      id: 'HK419',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 37,
    },
    {
      name: 'M4A1',
      id: 'M4A1',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 0,
    },
    {
      name: 'SCAR-H',
      id: 'Scar-H',
      hasModel: true,
      modelFov: 4,
      weaponType: 'automatic-rifles',
      unlockLevel: 10,
    },
  ],

  submachineGuns: [
    {
      name: 'MP7',
      id: 'MP7',
      hasModel: true,
      modelFov: 4,
      weaponType: 'submachine-guns',
      unlockLevel: 0,
    },
    {
      name: 'UMP-45',
      id: 'UMP45',
      hasModel: true,
      modelFov: 4,
      weaponType: 'submachine-guns',
      unlockLevel: 0,
    },
    {
      name: 'PP-2000',
      id: 'PP2000',
      hasModel: true,
      modelFov: 3.5,
      weaponType: 'submachine-guns',
      unlockLevel: 13,
    },
    {
      name: 'PP-19',
      id: 'PP19',
      hasModel: true,
      modelFov: 3.5,
      weaponType: 'submachine-guns',
      unlockLevel: 22,
    },
    {
      name: 'Kriss Vector',
      id: 'KrissVector',
      hasModel: true,
      modelFov: 4,
      weaponType: 'submachine-guns',
      unlockLevel: 35,
    },
    {
      name: 'MP5',
      id: 'MP5',
      hasModel: true,
      modelFov: 4.5,
      weaponType: 'submachine-guns',
      unlockLevel: 43,
    },
  ],

  marksmanRifles: [
    {
      name: 'MK-20',
      id: 'MK20',
      hasModel: true,
      modelFov: 4,
      weaponType: 'marksman-rifles',
      unlockLevel: 6,
    },
    {
      name: 'M110',
      id: 'M110',
      hasModel: true,
      modelFov: 4,
      weaponType: 'marksman-rifles',
      unlockLevel: 20,
    },
    {
      name: 'SVD',
      id: 'SVD',
      hasModel: true,
      modelFov: 4,
      weaponType: 'marksman-rifles',
      unlockLevel: 38,
    },
    {
      name: 'MK-14 EBR',
      id: 'MK14',
      hasModel: true,
      modelFov: 4,
      weaponType: 'marksman-rifles',
      unlockLevel: 50,
    },
  ],

  personalDefence: [
    {
      name: 'Honey Badger',
      id: 'HoneyBadger',
      hasModel: true,
      modelFov: 3.5,
      weaponType: 'personal-defence',
      unlockLevel: 40,
    },
    {
      name: 'P90',
      id: 'P90',
      hasModel: true,
      modelFov: 3,
      weaponType: 'personal-defence',
      unlockLevel: 52,
    },
    {
      name: 'GROZA',
      id: 'GROZA',
      hasModel: true,
      modelFov: 4,
      weaponType: 'personal-defence',
      unlockLevel: 94,
    },
  ],

  carbines: [
    {
      name: 'AS VAL',
      id: 'ASVAL',
      hasModel: true,
      modelFov: 3.5,
      weaponType: 'carbines',
      unlockLevel: 40,
    },
  ],

  lightSupportGuns: [
    {
      name: 'L86A1',
      id: 'L86A1',
      hasModel: true,
      modelFov: 6,
      weaponType: 'light-support-guns',
      unlockLevel: 0,
    },
    {
      name: 'M249',
      id: 'M249',
      hasModel: true,
      modelFov: 6,
      weaponType: 'light-support-guns',
      unlockLevel: 0,
    },
  ],

  sniperRifles: [
    {
      name: 'SSG 69',
      id: 'SSG69',
      hasModel: true,
      modelFov: 3,
      weaponType: 'sniper-rifles',
      unlockLevel: 0,
    },
    {
      name: 'SV-98',
      id: 'SV98',
      hasModel: true,
      modelFov: 3,
      weaponType: 'sniper-rifles',
      unlockLevel: 8,
    },
    {
      name: 'L96',
      id: 'L96',
      hasModel: true,
      modelFov: 3,
      weaponType: 'sniper-rifles',
      unlockLevel: 27,
    },
    {
      name: 'M200',
      id: 'M200',
      hasModel: true,
      modelFov: 3,
      weaponType: 'sniper-rifles',
      unlockLevel: 32,
    },
    {
      name: 'MSR',
      id: 'MSR',
      hasModel: true,
      modelFov: 3,
      weaponType: 'sniper-rifles',
      unlockLevel: 56,
    },
    {
      name: 'REM-700',
      id: 'REM700',
      hasModel: true,
      modelFov: 3,
      weaponType: 'sniper-rifles',
      unlockLevel: 72,
    },
  ],

  pistols: [
    {
      name: 'M9',
      id: 'M9',
      hasModel: true,
      modelFov: 2.5,
      unlockLevel: 0,
      weaponType: 'pistols',
    },
    {
      name: 'MP443',
      id: 'M9',
      hasModel: true,
      modelFov: 2.5,
      unlockLevel: 0,
      weaponType: 'pistols',
    },
    {
      name: 'USP',
      id: 'USP',
      hasModel: true,
      modelFov: 2.5,
      unlockLevel: 7,
      weaponType: 'pistols',
    },
    {
      name: 'UNICA',
      id: 'UNICA',
      hasModel: true,
      modelFov: 2.5,
      unlockLevel: 12,
      weaponType: 'pistols',
    },
    {
      name: 'GLOCK 18',
      id: 'GLOCK18',
      hasModel: true,
      modelFov: 2.5,
      unlockLevel: 13,
      weaponType: 'pistols',
    },
    {
      name: 'Desert Eagle',
      id: 'DESERT-EAGLE',
      hasModel: true,
      modelFov: 2.5,
      unlockLevel: 60,
      weaponType: 'pistols',
    },
  ],

  misc: [
    {
      name: 'Pickaxe',
      id: 'Pickaxe',
      unlockLevel: 0,
      weaponType: 'misc',
    },
    {
      name: 'Sledgehammer',
      id: 'Sledgehammer',
      unlockLevel: 0,
      weaponType: 'misc',
    },
  ],
}

export type WeaponsCategory = keyof typeof weapons
